name: Deploy (Dev)

on:
  workflow_dispatch:
  push:
    branches:    
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: bytesmith/dbt-bigquery:latest
      env:
        DBT_TARGET: dev
        DBT_PROJECT_DIR: ./wide_world_importers_dw
        DBT_ENV_SECRET_DEV_PROJECT_ID: ${{ secrets.DBT_ENV_SECRET_DEV_PROJECT_ID }}
        DBT_ENV_SECRET_DEV_KEYFILE_PRIVATE_KEY_ID: ${{ secrets.DBT_ENV_SECRET_DEV_KEYFILE_PRIVATE_KEY_ID }}
        DBT_ENV_SECRET_DEV_KEYFILE_PRIVATE_KEY: ${{ secrets.DBT_ENV_SECRET_DEV_KEYFILE_PRIVATE_KEY }}
        DBT_ENV_SECRET_DEV_KEYFILE_CLIENT_EMAIL: ${{ secrets.DBT_ENV_SECRET_DEV_KEYFILE_CLIENT_EMAIL }}
        DBT_ENV_SECRET_DEV_KEYFILE_CLIENT_ID: ${{ secrets.DBT_ENV_SECRET_DEV_KEYFILE_CLIENT_ID }}
        DBT_ENV_SECRET_DEV_KEYFILE_CLIENT_X509_CERT_URL: ${{ secrets.DBT_ENV_SECRET_DEV_KEYFILE_CLIENT_X509_CERT_URL }}
      volumes:
        - ${{ github.workspace }}/wide_world_importers_dw:/usr/app
        - ${{ github.workspace }}/dbt:/root/.dbt/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Resolve Dependencies
        run: dbt deps --project-dir=$DBT_PROJECT_DIR --profiles-dir=./dbt --target=$DBT_TARGET
      - name: Check Source Freshness
        run: dbt source freshness --project-dir=$DBT_PROJECT_DIR --profiles-dir=./dbt --target=$DBT_TARGET
      - name: Run Source Tests
        run: dbt test --select source:* --project-dir=$DBT_PROJECT_DIR --profiles-dir=./dbt --target=$DBT_TARGET
      - name: Add Seeds
        run: dbt seed --project-dir=$DBT_PROJECT_DIR --profiles-dir=./dbt --target=$DBT_TARGET
      - name: Run Transformations
        run: dbt run --project-dir=$DBT_PROJECT_DIR --profiles-dir=./dbt --target=$DBT_TARGET
      - name: Run Tests
        run: dbt test --exclude source:* --project-dir=$DBT_PROJECT_DIR --profiles-dir=./dbt --target=$DBT_TARGET
      - name: Generate Docs
        run: dbt docs generate --project-dir=$DBT_PROJECT_DIR --profiles-dir=./dbt --target=$DBT_TARGET
      - name: Upload Artifacts (Docs)
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: wide_world_importers_dw/target
